In [1]:
import pandas as pd
from function import compare_null_cols

dataset = pd.read_csv("../dataset/raw_dataset.csv")

In [2]:
dataset.head(5)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [3]:
dataset.isnull().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [4]:
dataset[dataset.columns[dataset.isnull().sum() != 0]].isnull().sum()

make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
condition       11820
odometer           94
color             749
interior          749
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [5]:
dataset[dataset["make"].isnull()].isnull().sum()

year                0
make            10301
model           10301
trim            10301
body            10301
transmission     1761
vin                 0
state               0
condition          87
odometer            4
color              15
interior           15
seller              0
mmr                 0
sellingprice        0
saledate            0
dtype: int64

In [6]:
compare_null_cols(dataset, "vin")

year            0
make            0
model           0
trim            0
body            0
transmission    0
state           0
condition       4
odometer        0
color           0
interior        0
seller          0
mmr             4
sellingprice    0
saledate        0
dtype: int64

In [7]:
dataset["make"] = dataset["make"].astype("string")

dataset["make"] = dataset["make"].str.strip().str.lower()

dataset["make"].value_counts().head(10)

dataset["make"].unique().size

67

In [8]:
dataset.groupby("make")["model"].value_counts()

make   model
acura  TL        2135
       MDX       1581
       TSX       1119
       RDX        420
       RSX        151
                 ...
volvo  S90          7
       940          2
vw     routan      12
       jetta        9
       beetle       3
Name: count, Length: 1014, dtype: int64

In [9]:
dataset["seller"].value_counts()

seller
nissan-infiniti lt               19693
ford motor credit company llc    19162
the hertz corporation            18299
santander consumer               15285
avis corporation                 12540
                                 ...
jimmy auto sale llc                  1
flynns auto sls & serv inc           1
ruthrauff auto sales llc             1
lsk automotive llc                   1
auto rental etc                      1
Name: count, Length: 14263, dtype: int64

In [10]:
# Checking NULL values
dataset["vin"].isnull().sum()

# Checking overall duplicate rows
dataset.duplicated().sum()

# duplicate "vin"s
dataset["vin"].duplicated().sum()

np.int64(8539)

In [11]:
# changing "state" into string
dataset["state"] = dataset["state"].astype("string")
dataset["state"].info()

dataset["state"] = dataset["state"].str.lower().str.strip()

# checking invalid states
invalid_state = dataset["state"][dataset["state"].str.len() > 2]

# checking invalid states count
invalid_state.value_counts().sum()

# checking valid states
valid_state = dataset["state"][dataset["state"].str.len() <= 2]

# Total valid states
valid_state.unique().size

dataset["state"].unique().size

<class 'pandas.core.series.Series'>
RangeIndex: 558837 entries, 0 to 558836
Series name: state
Non-Null Count   Dtype
--------------   -----
558837 non-null  string
dtypes: string(1)
memory usage: 4.3 MB

64

In [12]:
dataset.info()
dataset.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  string
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  string
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(9), string(2)
memory usage: 68.2+ MB

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [13]:
# changing datatypes

for col in ['make', 'model', 'trim', 'body', 'transmission', 'color', 'interior', 'seller']:
    dataset[col] = dataset[col].astype("string")
    dataset[col] = dataset[col].str.strip().str.lower()

dataset["saledate"] = pd.to_datetime(dataset["saledate"], errors = "coerce")

C:\Users\prana\AppData\Local\Temp\ipykernel_15264\1115804856.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dataset["saledate"] = pd.to_datetime(dataset["saledate"], errors = "coerce")
C:\Users\prana\AppData\Local\Temp\ipykernel_15264\1115804856.py:7: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  dataset["saledate"] = pd.to_datetime(dataset["saledate"], errors = "coerce")

In [ ]:
# Checking NULL values of 'saledate'

dataset["saledate"].isna().sum()

np.int64(38)

In [17]:
dataset.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,kia,sorento,lx,suv,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,2014-12-16 12:30:00+08:00
1,2015,kia,sorento,lx,suv,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,2014-12-16 12:30:00+08:00
2,2014,bmw,3 series,328i sulev,sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,2015-01-15 04:30:00+08:00
3,2015,volvo,s60,t5,sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,2015-01-29 04:30:00+08:00
4,2014,bmw,6 series gran coupe,650i,sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,2014-12-18 12:30:00+08:00